# Generated by Django 4.2.7 on 2024-03-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0019_diagnosis_alter_doctor_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="department",
            field=models.CharField(
                choices=[
                    ("Cardiologist", "Cardiologist"),
                    ("Dermatologists", "Dermatologists"),
                    (
                        "Emergency Medicine Specialists",
                        "Emergency Medicine Specialists",
                    ),
                    ("Allergists/Immunologists", "Allergists/Immunologists"),
                    ("Anesthesiologists", "Anesthesiologists"),
                    ("Colon and Rectal Surgeons", "Colon and Rectal Surgeons"),
                    ("Endocrinologists", "Endocrinologists"),
                    ("Gastroenterologists", "Gastroenterologists"),
                    ("Nephrologists", "Nephrologists"),
                    ("Urologists", "Urologists"),
                    ("Pulmonologists", "Pulmonologists"),
                    ("Neurologists", "Neurologists"),
                    ("Radiologists", "Radiologists"),
                    ("Rheumatologists", "Rheumatologists"),
                    ("Orthopedic Surgeons", "Orthopedic Surgeons"),
                    ("Ophthalmologists", "Ophthalmologists"),
                    ("Oncologists", "Oncologists"),
                    ("Psychiatrists", "Psychiatrists"),
                    ("Pathologists", "Pathologists"),
                    ("Pediatricians", "Pediatricians"),
                    ("Gynecologists", "Gynecologists"),
                    ("Obstetricians", "Obstetricians"),
                    ("General Surgeons", "General Surgeons"),
                    ("Family Physicians", "Family Physicians"),
                    ("Dentists", "Dentists"),
                    ("Physiotherapists", "Physiotherapists"),
                    ("Neonatologists", "Neonatologists"),
                    ("Geriatricians", "Geriatricians"),
                    ("Hematologists", "Hematologists"),
                    (
                        "Infectious Disease Specialists",
                        "Infectious Disease Specialists",
                    ),
                    ("Pain Management Specialists", "Pain Management Specialists"),
                    ("Plastic Surgeons", "Plastic Surgeons"),
                    ("Radiation Oncologists", "Radiation Oncologists"),
                    ("Sleep Medicine Specialists", "Sleep Medicine Specialists"),
                    ("Sports Medicine Physicians", "Sports Medicine Physicians"),
                    ("Vascular Surgeons", "Vascular Surgeons"),
                    ("Diagnostic Radiologists", "Diagnostic Radiologists"),
                    ("Interventional Radiologists", "Interventional Radiologists"),
                    ("Medical Geneticists", "Medical Geneticists"),
                    ("Nuclear Medicine Specialists", "Nuclear Medicine Specialists"),
                    (
                        "Occupational Medicine Specialists",
                        "Occupational Medicine Specialists",
                    ),
                    ("Osteopathic Physicians", "Osteopathic Physicians"),
                    ("Podiatrists", "Podiatrists"),
                    (
                        "Preventive Medicine Specialists",
                        "Preventive Medicine Specialists",
                    ),
                    ("Pulmonary Disease Specialists", "Pulmonary Disease Specialists"),
                    ("Reproductive Endocrinologists", "Reproductive Endocrinologists"),
                    ("Medical Oncologists", "Medical Oncologists"),
                    ("Thoracic Surgeons", "Thoracic Surgeons"),
                    ("Transplant Surgeons", "Transplant Surgeons"),
                    ("Urogynecologists", "Urogynecologists"),
                    ("Vascular Medicine Specialists", "Vascular Medicine Specialists"),
                ],
                default="Cardiologist",
                max_length=50,
            ),
        ),
    ]
